### PR TITLE
Support for saving Tune Params for different VTX power

### PR DESCRIPTION
**Pull request by lephiloux**
This pull request adds the ability to save params in DB and enable a set of values for different vtx power environments.

### CODE REVIEW

**Comment by scottgchin** [comment]
Just a thought, what if instead of default settings for 25, 200, and 600; a user could set up different profiles? For example, we have different locations with different RF environments , but if I could store track 1-25mw, track 1-200mw, track 2-25mw, etc. That would be pretty cool.

**Comment by lephiloux** [comment]
Just a question what relation should we use ? I see two way to do it.

**First:**
We use flat profile table with the following entries.
- name
- description
- calibration offset
- calibration threshold
- triger threshold

**Second**
we have a profile table, with track table, with tune params table

The profile table:
- id
- name
- track_id
- tune_params_id

The track table:
- id
- name
- description

The tune params table:
- id
- vtxpower
- calibration offset
- calibration threshold 
- triger threshold

First option is easier in terms of gui, user, development .
Second option is more flexible put more difficult to develop and in term of ui not so easy to have something easy to understand for user and probably a new html page will be needed.

What's your opinions about this ?

**Comment by scottgchin** [comment]
I would say go with the first option to keep it simple. What i'm picturing is that a user can adjust the parameters to fine tune, then they can hit a save button to add it to a profile, or something similar.

**Comment by lephiloux** [comment]
Done :-)

**Pull request merged**
