### PR TITLE
AJAX Develop

### PR DESCRIPTION
**Pull request by wolffman122**
Work on web interface to use AJAX so that the pages don't have to completely refresh.

### CODE REVIEW

**Comment by punkkills** [comment]
With all the files changed, this seems like the wrong branch to be pulling to.  @wolffman122, what was you starting point for this change?

**Comment by howflyquad** [comment]
This looks to be a pull request from the scottgchin/delta5_race_timer:develop branch to the scottgchin/delta5_race_timer:master branch. @wolffman122, going to assume this is a mistake and close the PR.

**Comment by wolffman122** [comment]
Hi Guys yes sorry it was a mistake.  I have been working off the master branch.  Very unfamiliar with github and was trying to start my own branch under master.  Guess I did that wrong.  But will keep working on turning some of the pages to use AJAX so they don't have to reload the whole page when you change an input.

**Comment by howflyquad** [comment]
@wolffman122 please have a look at the latest version-0.4 and develop branches. Massive updates were made compared to the master branch with regards to the web client.

**Pull request closed without merging**
