### PR TITLE
Add 'L' band frequencies to delta5server

### PR DESCRIPTION
**Pull request by ethomas997**
Adds 'L'-band frequencies to the entries in the 'delta5server' interface.  This requires that the nodes are running firmware with the 'freqMhzToRegVal' modification #63.

This PR also renames the band-ID letter for Raceband from 'C' or 'R'.  (The 'C' band-ID comes from a implementation shortcut in one of the open-source rx5808 projects; using 'R' makes more sense.)

--ET

### CODE REVIEW

**Comment by scottgchin** [comment]
L band frequencies are not legal in most places.  Would rather not encourage its use.

**Comment by ethomas997** [comment]
Well, it's your call, but there are lots of reasons for not trying to play the role of frequency police:

1. Frequency rules vary worldwide, so any given frequency can be "legal" in one place and not in another.
2. I've heard that for some pro-FPV-racing events, the organizers have gotten sanctions for more allowed frequencies.
3. Receivers supporting 48 channels are quite common, including lots of commercial gear (i.e., FuriousFPV goggle modules).  The guy behind the LaForge modules took a not-doing-it tack at first, but now his gear supports 48 channel with 'L' band.
4. The current software already supports several frequencies that are in the same class.
5. Low power equipment used indoors in a closed, private environment should be of no interest to regulators.
6. It's a receiver, not a transmitter in any case.
7. Putting these kinds of restraints on an open-source project will make developers look elsewhere to apply their talents.

**Comment by punkkills** [comment]
Scott, I agree with ethomas, FWIW.

**Comment by scottgchin** [comment]
Fair enough.  Let me take a look at the other function and test it on my box.

**Comment by brucesdad13** [comment]
I like Eric's addition :)

**Pull request merged**
